spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pgs_library
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true